# CS266: Fall 2019
# HW1
#
# Pratik Prajapati
# Ashraf Saber
#

import ECC
import MerkleTree as mtree

# script to test various functions of Merkle Tree class
# validateProof() is special function which would validate the proof generated by getMembershipProof()

data_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

m = mtree.MerkleTree(data_list)
m.generateTree()
m.postOrderPrintTree()
# print(m.getRootHash())
data = ECC.hash('f')
path = m.getMembershipProof(data)

if path is not None:
    print('path = ' + str(path))
else:
    print('membership failed')

isValid = m.validateProof(path)
if isValid:
    print('membership path is valid')
else:
    print('membership path is not valid')

print('labled proof ' + m.getLabledProof(data))
